- docs/libs/di-container.md
I've added a chapter on DI container usage. The path will need to be changed once the restructuring happens in the #15
> Add a DI container usage chapter

- website/pages/en/documentation.js
- website/pages/en/getting-started.js
- website/pages/en/index.js
Webpack dev server was throwing syntax errors for using `class` instead of `className`
> Replace class with className

- docs/frontend-libs.md
- docs/guides/blocks-block-from-components.md
- docs/guides/blocks-filer-block-attributes-override.md
- docs/guides/blocks-get-actions-helper.md
- docs/guides/blocks-render-block-view-helper.md
- docs/guides/blocks-structure-block-item.md
- docs/guides/blocks-structure-component.md
- docs/guides/blocks-structure-manifest.md
- docs/guides/config.md
- docs/guides/extending-classes.md
- docs/guides/i18n.md
- docs/guides/login.md
- docs/guides/manifest.md
- docs/guides/media.md
- docs/guides/menu.md
- docs/guides/taxonomy.md
- docs/libs.md
- website/sidebars.json
Adding docs for this PR https://github.com/infinum/eightshift-libs/pull/42
> Adding block-attributes-override filter

- website/core/Footer.js
- website/pages/en/getting-started.js
- website/pages/en/index.js
- website/static/css/custom.css
Change the layout of Github links in footer.
Add layout modifiers to flex container classes
Update the layout of cards in Getting started page.
> Layout updates

- docs/guides/enqueue.md
- docs/guides/extending-classes.md
- website/siteConfig.js
Did some minor rewording and added an example of how to extend the class when removing some hooks. I only added the example in the Admin_Enqueue part, the other two would follow the same logic.
> Update the enqueue docs

- website/docs/advanced/browsersync.md
- website/sidebars.js
Also added example for setting HTTPS sites.
> Add browsersync chapter

- website/docs/basics/blocks.md
> adding blocks intro chapter

- website/docs/basics/helpers-javascript.md
- website/docs/basics/helpers-php.md
Rename BEM selector functions for PHP and JS
> Rename BEM selector functions for PHP and JS

- website/docs/requirements.md
These 2 links weren't working, now they do.
> Broken links to theme / plugin

- website/docs/eightshift-frontend-libs.md
- website/docs/eightshift-libs.md
- website/docs/legacy/v4/advanced/aliases.md
- website/docs/legacy/v4/advanced/helpers-error-logger.md
- website/docs/legacy/v4/advanced/helpers-object.md
- website/docs/legacy/v4/guides/enqueue.md
Found few links that were not working so I just made minor changes.
> Legacy links in docs

- website/docs/basics/blocks-component-in-block.md
- website/docs/basics/helpers-javascript.md
I have updated the chapter with the new documentation
> Add documentation for filterComponentOptions

- website/docs/basics/blocks-styles.md
- website/docs/basics/helpers-javascript.md
- website/docs/basics/helpers-php.md
- new css variable options
- new helper
> updating variables docs

- website/docs/basics/helpers-javascript.md
- website/docs/basics/helpers-php.md
Changelog:
- updated chapter checkAttrResponsive
- updated checkAttr docs
> updated checkAttrResponsive, updated checkAttr

- website/docs/basics/webpack.md
This was needed for one of the recent projects and is a really useful thing.
> Update the webpack chapter with new entrypoint example.

- website/docs/basics/blocks-styles.md
- website/docs/basics/helpers-php.md
Changelog:
- added chapter on responsiveVariables and how to use them
- added chapter on variablesEditor and how to use it
> Added chapters on responsive variables and editor variables

- website/docs/basics/blocks-storybook.md
> Fix Storybook link and command

- website/docs/basics/dynamic-import.md
- website/sidebars.js
Updating:
- Dynamic blocks
- Sidebar.js
https://github.com/infinum/eightshift-docs/issues/111
> updating dynamic import

- website/docs/additional-libraries.md
- website/docs/advanced/custom-eightshift-frontend-libs-usage.md
- website/docs/advanced/custom-eightshift-libs-usage.md
- website/docs/advanced/the-eightshift-way.md
- website/docs/basics/blocks-styles.md
- website/docs/basics/tips-tricks.md
- website/sidebars.js
a few small example changes
- block styles
- additional libraries
- removing not used pages
> updating styles

- website/docs/legacy/v4/guides/menu.md
I couldn't find part of code when i tried searching project since method names changed to camel case, so i changed code to match latest changes in boilerplate.
> Updated code for Menu

- website/docs/welcome.md
Fixed a copy that I noticed was wrong. Feel free to give other suggestions for the new copy.
> Fix wrong copy

- website/docs/basics/basics-intro.md
- website/docs/basics/blocks-faq.md
- website/docs/basics/blocks-storybook.md
- website/docs/eightshift-frontend-libs.md
- website/docs/eightshift-libs.md
- website/docs/legacy/v4/advanced/aliases.md
- website/docs/legacy/v5/basics/basics-intro.md
- website/docs/legacy/v5/basics/blocks-storybook.md
- website/docs/legacy/v5/eightshift-frontend-libs.md
- website/docs/legacy/v5/eightshift-libs.md
- website/docs/legacy/v5/plugin.md
- website/docs/legacy/v5/theme.md
- website/docs/plugin.md
- website/docs/theme.md
- website/package-lock.json
- website/package.json
- website/sidebars.js
Mainly the chapter about adding libs on existing sites.
> Fix the broken links and update some chapters

- website/src/theme/sections/features/features.js
- website/src/theme/sections/get-started/get-started.js
- website/src/theme/sections/panels/panels.js
- website/src/theme/sections/why/why.js
After some discussion with @dingo-d, I've taken the liberty of rewriting the landing page copy a bit, as I noticed there was room to improve. 
Looking forward to feedback here!
> Improve landing page copy

- website/blog/2022-03-03-adding-blocks-wpcli.md
- website/docs/basics/architecture-concepts.md
Fixed some spacing issues and broken links
> Fix spacings and broken links

- website/docs/basics/blocks-component-in-block.md
Applied for latest release ATM
1. Fix broken links
2. Remove docs for non-existing PHP helpers
3. Update content
4. Add anchor link for a reference
5. Remove unnecessary fragments for an example
> Fixes & Updates for "Components in a Block" section

- website/docs/legacy/v6/basics/blocks-component-in-block.md
Apply for legacy version 6
1. Fix broken links
2. Remove docs for non-existing PHP helpers
3. Update content
4. Add anchor link for a reference
5. Remove unnecessary fragments for an example
> v6 - apply same Fixes & Updates in "Components in a Block" section

- README.md
- website/docs/migrations/6-7.md
- website/docs/migrations/7-8.md
- website/package.json
- website/sidebars.js
- website/src/theme/components/markdown/markdown.scss
> updating packages to the latest versions

- website/docs/basics/blocks-special-use-cases.md
- website/docs/migrations/7-8.md
- minor adjustments to the fix on eightshift libs
Waiting for https://github.com/infinum/eightshift-libs/pull/316 to be merged.
> Boolean fix on ES Libs - docs fix

- website/docs/basics/architecture-concepts.md
- website/docs/basics/autowiring.md
- website/docs/basics/library.md
Fix some old commands left in the docs.
> Fix typos and wrong commands in the docs

- website/docs/basics/architecture-concepts.md
- website/docs/basics/autowiring.md
- website/docs/basics/library.md
Fix the typos and wrong documentation commands
> Typo fixes

- website/blog/2022-12-13-using-cpts-and-taxonomies.md
Production release of `Using Custom Post Types and Taxonomies` blog post.
> Blog - CPTs and Taxonomies

- website/docs/plugin.md
- website/docs/theme.md
Fixed links to the basics intro page from sections:
- plugins
- theme
> FIx links to basics intro page

- website/docs/additional-libraries.md
- website/docs/basics/block-manifest.md
- website/docs/basics/blocks-component-in-block.md
- website/docs/basics/blocks-faq.md
- website/docs/basics/extending-classes.md
- website/docs/basics/helpers-php.md
- website/docs/basics/writing-styles.md
- website/docs/legacy/v8/basics/helpers-scss.md
- website/docs/plugin.md
- website/docs/theme.md
Some typo fixes and minor content updates. If there's anything that should be further expanded upon, just let me know.
I haven't used `renderPartial` helper yet, so if someone can describe in a more detail what it does, it would be really helpful 🙂
> Documentation fixes

- website/blog/2023-08-03-adding-custom-query.md
Blog post covering the topic of using custom queries in your project and a brief explanation of the service classes.
As always, feedback is much appreciated and if you think anything else should be covered here, let me know.
> Add a blog post about using a custom query

- website/package-lock.json
- website/package.json
- website/src/pages/sass.js
- website/src/pages/storybook.js
Changes:
- updated Docusaurus theme
- added classes for top borders on SASSDoc and Storybook pages
Fixes #281 (partially, the blue sidebar will be released with an FE Libs update), #280, and #269.
> Fixes & improvements

- website/docs/migrations/10-11.md
- website/docs/migrations/5-6.md
- website/docs/migrations/6-7.md
- website/docs/migrations/7-8.md
- website/docs/migrations/8-9.md
- website/docs/migrations/9-10.md
- website/package-lock.json
- website/package.json
- added migration guide for latest version
> updating migration guide

- website/blog/2023-05-05-making-your-project-multilingual.md
- website/blog/2024-02-01-making-your-project-multilingual.md
Blog post about making the project multilingual.
As always, feedback is very much appreciated 🙂
> Add blog post about I18n

- website/forms/php/filters/block/form/result-output-items.md
- website/forms/php/filters/block/form/result-output-parts.md
> hotfix filter name

- website/forms/php/shortcodes.md
> updating forms

- website/blog/2022-03-03-adding-blocks-wpcli.md
- website/blog/2022-04-25-using-assets.md
- website/docs/basics/block-structure.md
- website/docs/basics/blocks-component-structure.md
- website/docs/legacy/v4/guides/blocks-structure-block-item.md
- website/docs/legacy/v4/guides/blocks-structure-component.md
- website/docs/legacy/v5/basics/blocks-component-structure.md
- website/docs/legacy/v6/basics/block-structure.md
- website/docs/legacy/v6/basics/blocks-component-structure.md
- website/docs/legacy/v7/basics/block-structure.md
- website/docs/legacy/v7/basics/blocks-component-structure.md
- website/docs/legacy/v8/basics/block-structure.md
- website/docs/legacy/v8/basics/blocks-component-structure.md
- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
- website/src/theme/sections/os-projects.jsx
Sorry, just some "Saturday evening, slipped my mind" kind of things 😅
> Broken link fix

- website/blog/2024-03-28-using-post-templates.md
Adds a blog post that describes what post templates are and how to use them. If there's anything else that should be covered here, let me know.
> Add blog post about post templates

- website/package-lock.json
- website/package.json
- website/src/pages/devkit-components.js
- website/src/pages/playground.js
- website/src/theme/styles.css
- New loaders for Components and Playground that keep the user better informed about what's going on
- Reduced the size of Components docs theme so it should load way quicker
- Updated dependencies
\-
\-
> WP playground-related improvements

- website/src/pages/intro-post.txt
- website/src/pages/playground.js
Adds a new, simpler Playground implementation, showing off the new Tailwind theme.
**Note**: the .zip file URL will have to updated once this is pushed.
\-
\-
> Playground update

- website/src/pages/playground.js
- Added a warning if Service workers are not enabled, which are required for WP Playground
- Replaced the theme URL from my repo to Docs repo
\-
\-
> FE libs Tailwind - part 2

- playground-files/README.md
- Minor tweak to the example theme
- Added a readme about editing the example site.
\-
\-
> FE libs Tailwind - part 3

- website/src/pages/playground.js
Fixes Playground service worker detection (thanks SSG).
\-
\-
> FE libs Tailwind - part 3.5

- website/ui-components/components/component-showcase.js
Fixes Docusaurus being weird with more complex components and SSG.
\-
\-
> FE libs Tailwind - part 4.5

- website/package-lock.json
Guess `npm update <package name>` didn't work as it should have.......
\-
\-
> FE libs Tailwind - part 4.999

- website/docs/tailwind/getting-started.md
- website/docs/tailwind/helpers.md
- website/docs/tailwind/intro.md
- website/docs/tailwind/manifest.md
- website/package.json
- website/sidebars.js
- website/src/pages/playground.js
- website/ui-components/components/legacy-playground.js
- adds first round of docs for FE libs Tailwind
- updated demo theme
\-
\-
> FE libs Tailwind - part 5

- package-lock.json
- website/package-lock.json
> FE libs Tailwind - part 5.099

- website/src/pages/playground.js
Looks like WP Playground team fixed their bugs. Now we don't need the `login` param anymore.
\-
\-
> FE libs Tailwind - part 5.1

- website/package.json
- website/sidebars.js
Changes:
- added missing sidebar entry
- updated dependencies
> FE libs 13 migration guide - minor fixes

- website/docs/basics/blocks-patterns.md
Minor update to Patterns page:
- fixed broken links
- improved codeblock examples
> Update patterns page

- website/docs/tailwind/manifest.md
> TW example tweak

- website/docs/tailwind/getting-started.md
- website/docs/tailwind/manifest.md
- website/package-lock.json
- website/package.json
Changes:
- rewrote the Tailwind Manifest section to cover the new changes
- updated dependencies
> FE libs Tailwind 1.4.0 updates

- website/blog/2022-01-20-initial-setup.md
- website/docs/plugin.md
- website/docs/welcome.md
- updated old `create-wp-project `
> Docs - Update npx command

- website/docs/migrations/13-14.md
- website/sidebars.js
> Migration 13-14

- website/docs/migrations/13-14.md
Updated migration guide for 13-14 : https://eightshift.com/docs/migrations/13-14
> Update migration 13-14 guide

- website/docs/migrations/13-14.md
Migration guide update for `getProjectPaths` method
> Update migration 13-14 - getProjectPaths method
